name: Update File

on:
  schedule:
    - cron: "0 4 * * *"

env:
  TZ: America/New_York

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          cd ${{ github.workspace }}
          git config --global user.name delucia527
          git config --global user.email "delucia527@gmail.com"
      - name: Download file
        run: curl -L -o grandmas_yeast_infection.xml.gz https://epgshare01.online/epgshare01/epg_ripper_US1.xml.gz
      - name: Commit and push changes
        run: |
          git add grandmas_yeast_infection.xml.gz
          git commit -m "Update file"
          git push
